### ISSUE TITLE
Unable tu run analysis with Core v9.0.0

### ISSUE THREAD

**Issue by gian1200** [etnetera/owasp-dependency-check#18]
Dependency-Check Core version: 9.0.0 doesn't work. 
8.4.x versions worked fine

Log is also broken:
```sh
owasp-dependency-check: Dependency-Check Core path: C:\<project path>\dependency-check-bin\dependency-check\bin\dependency-check.bat
owasp-dependency-check: Dependency-Check Core version: 9.0.0
owasp-dependency-check: Running command:
 C:\<project path>\dependency-check-bin\dependency-check\bin\dependency-check.bat --out=./dependency-check-reports --project="<project name>" --data=/tmp/dependency-check-data --format=HTML --format=JSON --scan=package-lock.json
Error: Command failed: C:\<project path>\dependency-check-bin\dependency-check\bin\dependency-check.bat --out=./dependency-check-reports --project="<project name>" --data=/tmp/dependency-check-data --format=HTML --format=JSON --scan=package-lock.json

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 13,
  killed: false,
  signal: null,
  cmd: 'C:\\<project path>\\dependency-check-bin\\dependency-check\\bin\\dependency-check.bat --out=./dependency-check-reports --project="<project name>" --data=/tmp/dependency-check-data --format=HTML --format=JSON --scan=package-lock.json'
}
```

Already tried deleting `dependency-check-bin` and `C:\tmp\dependency-check-data` folders.

As a workaround, is there a way to force a specific core version to use?

**Comment by gian1200** [comment]
May be related to this https://github.com/jeremylong/DependencyCheck#900-upgrade-notice

**Comment by michalszelagsonos** [comment]
I can successfully run the check with `9.0.2`.  There are several issues related to API key management that users now have to be aware of.  Essentially, I think this issue should be closed.

**Comment by gian1200** [comment]
Yes and no. I agree that v9.0.2 seems to fix the issue (at least it no longer catastrophically fails).
For anyone reading this:
- To upgrade to latest version, you need to delete `dependency-check-bin` folder (there seems to be no autoupdate)
- If you encounter the same issue on 9.0.2, take into consideration that a DB purge (--purge) might be necessary).

Having said that, it is also true that the logs (at least on windows) seems to be broken. Running `dependency-check.bat` directly gives almost no log, except for that broken stack trace when it fails. Running `dependency-check.sh` gives a REALLY USEFUL information. Ideally, both should give the same information.
