### ISSUE TITLE
Expose a CLI option to set dependency-check version in use

### ISSUE THREAD

**Issue by michalszelagsonos** [etnetera/owasp-dependency-check#19]
Given that `9.0.0` and `9.0.1` have a problem, specifically this one: https://github.com/jeremylong/DependencyCheck/issues/6157 it seems prudent to expose a parameter to allow for pinning to a specific version.  Currently, the code just checks for latest available and uses that which is a pretty risky proposition if there is a regression in a new release.  Giving a user an option to set specific version seems like a very useful feature that favors stability.  Users that just want to update to latest all the time can stick with current behavior

**Comment by centi** [comment]
Thank you for the PR>

**Comment by vincego** [comment]
Please be aware that this option doesn't work when binDir parent folder (defaults to ./dependency-check-bin) doesn't exist because cleanDir function won't create binDir recursively and fails with "ENOENT: no such file or directory, mkdir".
