### ISSUE TITLE
Unable to run check with latest dependency-check (v10)

### ISSUE THREAD

**Issue by gian1200** [etnetera/owasp-dependency-check#26]
Now that v10 has been released, download script fails. Regex expect a 1 digit version, but latest now has 2

owasp-dependency-check version: 0.0.21
![image](https://github.com/etnetera/owasp-dependency-check/assets/405347/d02cdc4d-94ac-407b-9217-a612fd49702e)

Workaround: 
change first `\d` with a 10

Seems to be already fixed on code (4 months ago), but new release hasn't been pushed. `0.0.21` is from [2 years ago](https://www.npmjs.com/package/owasp-dependency-check)
https://github.com/etnetera/owasp-dependency-check/commit/7c9b6eb71cd97b33d8067ce5496877be3dcdc525

Also: https://github.com/etnetera/owasp-dependency-check/pull/25

**Comment by centi** [comment]
PR #25 is merged and version 0.22 is out. The new RE should work with multidigit versions of the binary.
