### ISSUE TITLE
installing owasp for the first time in my app

### ISSUE THREAD

**Issue by andradenathan** [etnetera/owasp-dependency-check#27]
Hey guys, there's something making me questionable about using owasp-dependency-check in my front-end app.
Do I need also install Java to run the lib with npm or the Node.js Wrapper has its own transpiler or something to understand the binary Java code?

**Comment by centi** [comment]
Hi, this is just a wrapper for the original CLI tool, so you need all the requirements that the CLI has. So yes, you also need to have Java installed separately.
