### ISSUE TITLE
Error downloading files

### ISSUE THREAD

**Issue by gian1200** [etnetera/owasp-dependency-check#28]
There seems to be a change. There is a new folder "latest". The zip file is no longer at the root

- OS: Windows 11
- "owasp-dependency-check": "^0.0.23"

```shell
> owasp-dependency-check -f HTML -f JSON

owasp-dependency-check: No Dependency-Check Core executable found. Downloading into: <absolute projectpath>\dependency-check-bin\latest
node:internal/fs/promises:858
  return await PromisePrototypeThen(
         ^

Error: ENOENT: no such file or directory, mkdir '<absolute projectpath>\dependency-check-bin\latest'
    at async mkdir (node:internal/fs/promises:858:10)
    at async cleanDir (<absolute projectpath>\node_modules\owasp-dependency-check\lib\utils.js:63:3) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '<absolute projectpath>\\dependency-check-bin\\latest'        
}

Node.js v20.17.0
```

PS: it's trying to download 10.0.1. However, latest is 10.0.4 (https://github.com/jeremylong/DependencyCheck/releases)

**Comment by gian1200** [comment]
Found the issue. Given that there is a new "latest" folder, mkdir needs recursive parameter/option to be true

https://github.com/etnetera/owasp-dependency-check/blob/0154f2d7be2e2ab66f539bb9cab66267cbf66d16/lib/utils.js#L55-L64

### Suggested change:

```js
async function cleanDir(dir) {
  const cleanErr = await rimrafPromise(dir);

  if (cleanErr) {
    console.error(cleanErr);
    return;
  }

  await mkdir(dir, { recursive : true }); <-- this
}
```

### Result:

![image](https://github.com/user-attachments/assets/16644e14-b8fb-454e-8338-30ba0346340d)

**Comment by gian1200** [comment]
As a workaround (until fix is released) one can manually create `dependency-check-bin/latest/` folder

**Comment by centi** [comment]
@gian1200 Thanks for the PR. I released the fix: https://www.npmjs.com/package/owasp-dependency-check/v/0.0.24
