### ISSUE TITLE
Upgrading Causes Errors

### ISSUE THREAD

**Issue by msaperst** [etnetera/owasp-dependency-check#7]
Upgrading to 0.0.19 doesn't work, it throws the error:
`Error: Cannot find module 'fs/promises'`
This appears to usually caused by missing node modules or package-lock.json files, but all of these are present.

**Comment by centi** [comment]
The module `fs/promises` is available in Node.js version 14+. Please try upgrading your Node.

I'll update the `package.json` and add this requirement.

**Comment by centi** [comment]
I published a new version (0.0.21), which has the required Node.js version specified in the `package.json`. This information is now in the `README.md` aswell.

Installing with an unsupported version (lower than 14) will show warnings in the console.
